services:
  - postgresql
  - memcached
language: ruby
rvm:
  - 2.7.1
dist: xenial
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
before_install:
  - gem install bundler -v 2.1.4
  - sudo apt-get install -y postgresql-server-dev-11
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
script: bundle exec rake test
